server:
  port: 8888

logging:
  file:
    path: D:\\LOG

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    eviction-interval-timer-in-ms: 6000
    wait-time-in-ms-when-sync-empty: 6000
    enable-self-preservation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: eureka
  security:
    user:
      name: eureka
      password: wuyue930912
      roles: SUPERUSER
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

