server:
  port: 80

logging:
  file:
    path: D:\\LOG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id:  127.0.0.1:${spring.application.name}:${server.port}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: maintain
          uri: lb://maintain
          predicates:
            - Path=/maintain/**

        - id: websocket
          uri: lb://websocket
          predicates:
            - Path=/websocket/**

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8