spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3308/pethub?characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: wuyue930912